(library
 (name terminal_presentation)
 (modules presentation state)
 (libraries core hardcaml_workbench_protocol)
 (preprocess
  (pps ppx_jane))
 (inline_tests
  (flags
   (-source-tree-root .))))

(executable
 (name main)
 (modules main)
 (public_name hardcaml-workbench)
 (package hardcaml_workbench)
 (libraries
  async
  bonsai
  bonsai_term
  core
  core_unix.command_unix
  hardcaml_workbench_native_http
  hardcaml_workbench_protocol
  terminal_presentation)
 (preprocess
  (pps ppx_jane bonsai.ppx_bonsai))
 (lint
  (pps ppx_js_style)))
